name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: base
        uses: docker/build-push-action@v2
        with:
          context: ./base
          tags: remidiniz/csgo
          push: false
      - name: sourcemod
        uses: docker/build-push-action@v2
        with:
          context: ./sourcemod
          tags: remidiniz/csgo:sourcemod
          push: false
      - name: pug-practice
        uses: docker/build-push-action@v2
        with:
          context: ./pug-practice
          tags: remidiniz/csgo:pug-practice
          push: false
